import Head from 'next/head'
import styles from '@/styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.content}>
          <img src='./../assets/images/ty-lue.jpg' alt='ty lue stupid ass head' />
          <h1 className='title'>hi, i'm ruddel</h1>
          <p className='flavour-text'>Sorry, but there's not a whole lot happening here just yet. Come back later!</p>
        </div>
      </main>
    </>
  )
}
